batch_size: 21
num_epochs: 1000
use_pretrained_model: True
warmup_start: False
lr: 0.00001
split_sizes: 0.9
dataset_dirname: "./dataset-2"
checkpoint_filename: "./checkpoints_saved/01_checkpoint_1000.pkl"